### ISSUE TITLE
Blog and blogpage snippets not compatible with Yello 0.7.1

### ISSUE THREAD

**Issue by schulle4u** [nasendackel/yellow-comments#16]
Hello, 

as it seems the `content-blog` and `content-blogpages` snippet files provided with the comments plugin are not compatible with latest version of Yellow. 

* The blog sidebar is not shown because the appropriate php snippet is missing. 
* When clicking on a blog post in the overview, I'm being redirected to the wrong location and an error 404 is given. This only happens when Yellow is installed in a subdirectory, e.g. `/yellow/blog/post` points to `/blog/post` instead. 

Hope this can be fixed and this nice idea is still under development, I'd like to test this after switching from WordPress. 

Steffen

**Comment by ghost** [comment]
Hi, will have a look at it. The development was a bit quite. I use the plugin within my blog. Maybe you will have a working version in the next few weeks.

**Comment by ghost** [comment]
@schulle4u 

You can customize the two snippets yourself. There are the details

`$yellow->page->getLocation()`

With

`$yellow->page->getLocation(true)`

to replace. After that, the problems you mentioned should no longer exist. I do not use the sidebar and have not tested it. That's the way it was with me ;-) I've made it myself now, it works so far in the test mode without further problems. Since I do not know about Github ... I did not dare to change it ;-)

Greetings - Jan

PS: I like the plugin but very good! I do not like Disqus

**Comment by schulle4u** [comment]
Thanks Jan, I'll try your suggestions soon. 

Steffen

**Comment by ghost** [comment]
@schulle4u 
Hi Steffen,

you can check my changes [here](https://github.com/JanYellow/yellow-comments) if it helps. I had made some other changes. Sorry but I do not know much about Github.

Greetings - Jan

**Comment by wunderfeyd** [comment]
The main idea was to insert some callbacks (maybe these are there already) into the original blog source files of yellow. This would allow to insert code at every comment and under a blog page. But I've to discuss with @markseu first, since my development on this plugin was indeed very quite for the last year. But nevertheless I'm open for suggestions or alternatives.

**Comment by markseuffert** [comment]
@wunderfeyd Let me do one more release please, then we can ~~break the API~~ make the API better. Let's discuss the changes needed for this plugin this weekend, if you want. Help is always welcome. :smile:

**Comment by wunderfeyd** [comment]
No problem. I like to break things, especially APIs . But I can wait... in the meanwhile I break other things to warm up. 😈

**Comment by markseuffert** [comment]
Please try the new API, I added a page context to core events/callbacks. Let me know if this works.

**Comment by GiovanniSalmeri** [comment]
I have just finished a partial rewrite of the plugin (some features added, a few features dropped, bugs corrected, refactoring of the code, a new CSS etc.). All works beautifully with the latest API. Please allow me the time for some testing more, and above all for learning the basics of Github, and I will publish all. Hope it will be useful to somebody!

**Comment by wunderfeyd** [comment]
@GiovanniSalmeri sounds great. Please create a pull request if you are ready. I'm happy to review and accept nearly everything that pushes this Yellow plugin into a good direction. If you have questions about the old code or you need to crosscheck something, let me know. Happy coding/testing.

**Comment by GiovanniSalmeri** [comment]
@wunderfeyd My fork is now at <https://github.com/GiovanniSalmeri/yellow-comments>. I have written a detailed Changelog and Readme, I hope that they give an idea of what I tried to accomplish. I wanted for a site of mine a commenting system very usable and light, esthetically pleasing and rather well-protected against spam, and your comments plugin was very close to my ideal! Please tell me if you want me to create a pull request, I understand that not everything I have made would like to everybody. Thank you very much!

**Comment by wunderfeyd** [comment]
@GiovanniSalmeri It's far better than I have thought (I didn't tried it but read the code and crawled through the diff, searched for possible problems and so on). Since I've no active installation by myself with such a plugin enabled to work with (a reason for the slow development in the past) I would offer you to take over the repository.

The reasons:
* You have a need to develop it further (for me it's the opposite)
* Your code is good (nothing to complain at first sight)
* You've already changed the paths and images for your account in your fork :)

Are you interested? If not, go ahead and send me a pull request. ;)

**Comment by schulle4u** [comment]
Great work @GiovanniSalmeri, just installed it on one of my sites. 

* There is an error when no `commentsModerator` is configured, the plugin falls back to site author instead of site email. Pull request already sent to fix this. :)
* Please consider setting gravatar support to 0 by default for privacy reasons. 

Steffen

**Comment by GiovanniSalmeri** [comment]
@schulle4u Thank you very much, commited! Regarding gravatar, you are right, I will change this.

**Comment by GiovanniSalmeri** [comment]
@wunderfeyd Thank you very much for your proposal! I have thought about it a little: I accept with pleasure. I am an absolute beginner as regards Github, but this repository was recently rather quiet: if it continues like this I will have the time to learn calmly Github without risking too many disasters...

**Comment by wunderfeyd** [comment]
@GiovanniSalmeri Okay, good decision. I've updated this repository from your fork. I'll begin with the ownership transfer in a few moments, so you can keep all stars and backlinks.

**Comment by wunderfeyd** [comment]
@GiovanniSalmeri GitHub told me you have to rename your fork or delete it before ownership transfer. Because the names are the same. :)

**Comment by GiovanniSalmeri** [comment]
@wunderfeyd Renamed just now

**Comment by wunderfeyd** [comment]
@GiovanniSalmeri Ownership transfer request should be in your inbox.

**Comment by GiovanniSalmeri** [comment]
@wunderfeyd Still nothing in my inbox, is it normal?

**Comment by wunderfeyd** [comment]
@GiovanniSalmeri Hmm, I tried again now. GitHub states: "GiovanniSalmeri already has a repository in the wunderfeyd/yellow-comments network". You probably have to delete it first. :( It seems one can't move to a user who has already a fork.

**Comment by GiovanniSalmeri** [comment]
> @GiovanniSalmeri Hmm, I tried again now. GitHub states:
> "GiovanniSalmeri already has a repository in the
> wunderfeyd/yellow-comments network". You probably have to delete it
> first. :(

Done!

-- 
Giovanni Salmeri
http://mondodomani.org/pers/salmeri/

**Comment by wunderfeyd** [comment]
" Repository transfer to GiovanniSalmeri requested " ... please accept. :)

**Comment by wunderfeyd** [comment]
Congratulations... Please update the plugin reference in https://github.com/datenstrom/yellow-plugins

Happy coding, many stars and keep up the good work.

**Comment by GiovanniSalmeri** [comment]
Thank you very much, all seems in order!

**Comment by schulle4u** [comment]
I'm closing my issue for now since the initial problem is no longer relevant.
