### ISSUE TITLE
Names of developers

### ISSUE THREAD

**Issue by GiovanniSalmeri** [nasendackel/yellow-comments#17]
@nasendackel @wunderfeyd In the readme and code templates there is a place for the developers. Now I have written "Authors", but it isn't very informative... I think I should write your (real?) names, shouldn't I? And also my name? And other contributors'? Thank you!

**Comment by wunderfeyd** [comment]
I can speak for my self only. But here's my point of view. I'm very happy with doing initial work and helping in the background where I can and my time allows. The working product is what the development is about. So for me personally it's not relevant to be on a list of developers/authors. You on the other hand, should write down your name to the list because you are the owner/maintainer of the plugin, you know most about it and the plugin users need someone to get in touch with in first place. (The other people here will try to help also in any case.)

I've no opinion about other contributors... In the end all of our contacts are visible in the git commit log. I think that's enough. :)

**Comment by GiovanniSalmeri** [comment]
After hearing from nasendakel, I added the (github) names of both in the readme. So I am more in peace! :-)
