### ISSUE TITLE
Great work so far and an error!

### ISSUE THREAD

**Issue by ghost** [nasendackel/yellow-comments#4]
Hi wunderfeyd,

I just updated to your last chance. Everytime I write a test comment, I just get a "An error occured. Please try again later." Is there a way to debug?

**Comment by wunderfeyd** [comment]
I guess the problem is the files are created inside the content directory now. You can change the `commentsDir` setting to `comments/` than the old behaviour can be achived. Otherwise check permissions on the content directory. Also the `contactEmail` has beed replaced by `commentEmail`. (Hmm looks like a typo should be `commentsEmail`)

Still a lot of things to do. Yes and we need to inherit the Yellow debug flag for better debugging output. If all fails one has to add some `echos` to the code to check where the code breaks. 

And well yes we have no documentation of the settings and installation process right now. :\

**Comment by ghost** [comment]
Maybe a stupid question: But in what file do I set the commentEmail?

**Comment by wunderfeyd** [comment]
The plugin is using the settings system of Yellow with `system/config/config.ini`. This is where your 
settings belong to.

A short overview over the settings so far:
- `commentsDir` (default: `` (empty))
  
  The location where your comment files are stored, if empty the files are stored within the content directory by using the `commentsExtension` setting.
- `commentsExtension` (default: `-comments`)  
  
  If your comments are stored within the content files, it's needed to distinguish between normal content and comments. If a comment is stored the base file path is needed and extended with the extension given. For example `test.txt` would become `test-comments.txt`.
- `commentsTemplate` (default: `system/config/comments-template.txt`)  
  
  When a new comment file is created, one could set a default content for the head of the file. Maybe we can display it later. At the moment it's used to hide the comments from the page visitor and for better webinterface integration.
- `commentsSeparator` (default: `----`)
  
  When having multiple comments, the separator is used to split the comment file into separate comments.
- `commentsAutoAppend` (default: `0`)
  
  If this flag is set to `1`, entered comments are automatically added to the comment file. No need to do it by yourself.
- `commentsAutoPublish` (default: `0`)
  
  If a comment is added automatically, you may wish the comment is published immediately. If you set this to `1` you have to remove new comments instead of adding them.
- `commentsMaxSize` (default: `10000`)
  
  In case someone tries to overflow your webspace you can limit the comment files to the needed maximum size.
  - `commentsSpamFilter` (default: `href=|url=`)
  
  The message/comment input field is checked against this filter, to ensure no unwanted content is within this message.
- `commentEmail` soon `commentsEmail` (needed)
  
  This setting has to be set at the moment. All comments entered are mailed to this address.

I'll do some changes/additions to the plugin this week. For example I would like to have a possibility to activate/deactivate a comment from within my mail, so I don't have to use any editor to publish comments. Then a timeout for not published comments would be nice. In case you don't publish a comment the system will remove it automatically from the comment file after some time, to free allocated space. Also a blacklist would be great. If you choose to hide comments (due to bad user behaviour for example) on the entire website. These are more or less technical/administrative things.

On the user/visitor side it would be nice to have, individual (or better random) icons for users. Emoticons and maybe Markdown are good also. 

Much to do. I don't expect a prefect plugin the next days. I can spent half an hour a day for this only and maybe someone wants to help. That's why you see just little commits instead of a big final commit.

Let me know if you got your comments working. When ready it should be easy to use, with minimal effort on the administrative side (at least this is the goal).

**Comment by wunderfeyd** [comment]
Btw. just saw your last commits. Great work too. Do you have any goals you want to achieve or do you need different features? Maybe we can combine our ideas or better we can develop better with the combined goals in mind. ;)

**Comment by ghost** [comment]
Thanks. No Ideas at the moment. At the weekend I have the plan to add the changes to the "default" yellow blog template. So it would be easier for new users.

**Comment by wunderfeyd** [comment]
Note: `commentEmail` is now `commentsEmail`

**Comment by wunderfeyd** [comment]
Going to copy the setting description to the readme.md with the next commit.
