### ISSUE TITLE
Comments are published by the feed plugin

### ISSUE THREAD

**Issue by ghost** [nasendackel/yellow-comments#5]
Hi, 

when you store the comments-file in the content-folder, they are published by the feed-plugin. Maybe it's a good idea to exclude.

**Comment by wunderfeyd** [comment]
Thank you for cross checking this. Hmm it's interesting. Have to check if the same issue applies to the draft plugin, because I use the same methods to hide these pages. I see a `FeedFilter` in the plugin code which filters for template types but the page visible attribute isn't used. I'll investigate this issue these days.

**Comment by wunderfeyd** [comment]
Can't reproduce. The comment pages are automatically invisible in my test feed. Do you have an example?

**Comment by ghost** [comment]
Oh, sorry. My mistake. I didn't have the "Parser: Comments" in the comments-file

**Comment by wunderfeyd** [comment]
No problem. At least we both have tested it now. :)
