### ISSUE TITLE
Error with append and autopublished

### ISSUE THREAD

**Issue by ghost** [nasendackel/yellow-comments#6]
When I turn append and auto published on. I get this error:

Warning: flock() expects parameter 1 to be resource, string given in /www/htdocs/w0080f53/nasendackel/blog/system/plugins/comments.php on line 180

Warning: flock() expects parameter 1 to be resource, string given in /www/htdocs/w0080f53/nasendackel/blog/system/plugins/comments.php on line 184

**Comment by wunderfeyd** [comment]
Thanks for the hint. Corrected in commit https://github.com/nasendackel/YellowComments/commit/3760b33800fa5a196857bc4924b6e641e01cfbf6.

**Comment by ghost** [comment]
Thanks! Works. Just a security question. I don't have to be logged in for approve a comment. It is safe because of the aid= ?

**Comment by wunderfeyd** [comment]
Yes, it should be. An attacker shouldn't be able to read your mails and the browser history. The aid is a cryptographic random number and should be very hard to guess. But nevertheless you are right, it would be more secure to have a real authentication. (But there would remain problems if you don't use https, since your password is transferred in plain text of the wire otherwise).

What do you think? Would it be useful? I'm undecided here. If it's needed I would add it.

**Comment by ghost** [comment]
Well, I honestly don't really know. Maybe it feels better to log-in to approve a comment. Otherwise the current way for me is perfect. I can approve a comment just by mail on my iphone :)

**Comment by wunderfeyd** [comment]
Yeah, I had simplicity in mind. But I add it to the task list. Btw. good idea: I'll open a ticket/issue with a todo list. Maybe one or the other has an additional idea or wish.
